Repository swapmyvote/swapmyvote, pull requests merged in 2019-11, with the labels that each got.

#51 Change to rspec
  .rspec
  Gemfile
  Gemfile.lock
  config/application.rb
  spec/controllers/static_pages_controller_spec.rb
  spec/fixtures/.keep
  spec/fixtures/constituencies.yml
  spec/fixtures/parties.yml
  spec/fixtures/polls.yml
  spec/fixtures/potential_swaps.yml
  spec/fixtures/swaps.yml
  spec/fixtures/users.yml
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/controllers/constituencies_controller_test.rb
  test/controllers/home_controller_test.rb
  test/controllers/sessions_controller_test.rb
  test/controllers/share_controller_test.rb
  test/controllers/static_pages_controller_test.rb
  test/controllers/users_controller_test.rb
  test/fixtures/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/mailers/previews/user_mailer_preview.rb
  test/mailers/user_mailer_test.rb
  test/models/.keep
  test/models/constituency_test.rb
  test/models/party_test.rb
  test/models/poll_test.rb
  test/models/potential_swap_test.rb
  test/models/swap_test.rb
  test/models/user_test.rb
  test/test_helper.rb
Labels: tech debt

#50 Copy updates 2019.2
  API.md
  README.md
  app/views/home/index.html.haml
  app/views/layouts/application.html.haml
  app/views/static_pages/about.html.haml
  app/views/static_pages/contact.html.haml
  app/views/static_pages/faq.html.haml
  app/views/user/share/show.html.haml
  app/views/user/swaps/_list_potential_swaps.html.haml
  app/views/user/swaps/_searching_for_swap.html.haml
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/no_swap.haml
  app/views/user_mailer/not_swapped_follow_up.haml
  app/views/user_mailer/partner_has_voted.html.haml
  app/views/user_mailer/reminder_to_vote.html.haml
  app/views/user_mailer/swap_cancelled.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/user_mailer/swap_not_confirmed.html.haml
  app/views/user_mailer/welcome_email.html.haml
  app/views/users/edit.html.haml
Labels: frontend

#58 Improve 'user swap' poll charts
  app/assets/javascripts/polls.coffee
  app/assets/stylesheets/profile.scss
  app/views/layouts/application.html.haml
Labels: enhancement, frontend, impact

#61 Rubocop config tweaks
  .rubocop.yml
Labels: tech debt

#69 [rubocop] fix Style/GuardClause (#57)
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/user/swaps_controller.rb
  app/controllers/user/vote_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/models/user.rb
Labels: easy, tech debt

#82 Issue 8 prep specs for new constituencies
  .editorconfig
  Gemfile
  Gemfile.lock
  spec/controllers/user/constituencies_controller_spec.rb
  spec/requests/user/constituencies_spec.rb
  spec/views/user/constituencies/edit.html.haml_spec.rb
  spec/views/user/constituencies/update.html.haml_spec.rb
Labels: backend, tech debt

#83 Autocomplete on constituency lookup
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/autocomplete.js
  app/assets/stylesheets/application.css
  app/assets/stylesheets/autocomplete.scss
  app/views/user/constituencies/edit.html.haml
Labels: enhancement, frontend

#75 Cookie consent
  app/assets/javascripts/cookie_consent.coffee
  app/assets/stylesheets/home.scss
  app/views/layouts/application.html.haml
Labels: GDPR, frontend

#91 Only require email updates / notices for significant changes
  app/views/static_pages/privacy.html.haml
Labels: GDPR, easy, frontend

#92 don't prevent deep-linking
  app/views/static_pages/terms.html.haml
Labels: GDPR, easy, frontend

#97 Issue 8 more specs for constituencies
  spec/controllers/user/constituencies_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/helpers/polls_helper_spec.rb
  spec/models/constituency_spec.rb
  spec/models/poll_spec.rb
  spec/models/user_spec.rb
Labels: backend, granularity, tech debt

#105 add .travis.yml (#39)
  .rubocop.yml
  .travis.yml
Labels: easy, tech debt

#106 bundle update
  Gemfile.lock
Labels: tech debt

#100 Update branding and background for 2019
  app/assets/images/facebook_sharing_banner.jpg
  app/assets/images/favicon_16.png
  app/assets/images/favicon_32.png
  app/assets/images/favicon_64.png
  app/assets/images/logo_facebook.png
  app/assets/images/logo_high_res.png
  app/assets/images/logo_nav.png
  app/assets/images/logo_nav@2x.png
  app/assets/images/pattern.png
Labels: brand, frontend

#113 anonymize IPs for Google Analytics (#101)
  app/views/layouts/_google_analytics.html.haml
Labels: GDPR, easy

#117 Helper specs
  spec/helpers/application_helper_spec.rb
Labels: tech debt

#121 SCSS linting
  .scss-lint.yml
  Gemfile
  Guardfile
  Rakefile
  app/assets/stylesheets/_mixins.scss
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/button.scss
  app/assets/stylesheets/cookieconsent.scss
  app/assets/stylesheets/footer.scss
  app/assets/stylesheets/home.scss
  app/assets/stylesheets/mailchimp.scss
  app/assets/stylesheets/modal.scss
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/profile.scss
  app/views/home/_swaps_open.html.haml
Labels: tech debt

#124 Fix API and add more tests
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  config/environments/test.rb
  spec/controllers/api_controller_spec.rb
  spec/controllers/home_controller_spec.rb
  spec/factories/party.rb
  spec/helpers/application_helper_spec.rb
  spec/support/swaps_closed.rb
  spec/support/user_sessions.rb
Labels: backend, bug, tech debt

#127 ditch /uk from API path (#80)
  API.md
  config/routes.rb
Labels: impact

#119 Add phone verification via MessageBird (#7)
  .env.example
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/verify_mobile.scss
  app/controllers/mobile_phone_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/models/mobile_phone.rb
  app/models/user.rb
  app/services/swap_my_vote/message_bird.rb
  app/views/mobile_phone/verify_create.html.haml
  app/views/mobile_phone/verify_token.html.haml
  app/views/users/edit.html.haml
  config/routes.rb
  db/migrate/20191117155600_create_mobile_phones.rb
  db/migrate/recreate-users.sql
  db/schema.rb
  spec/controllers/mobile_phone_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/mobile_phone_spec.rb
  spec/models/user_spec.rb
  spec/views/mobile_phone/verify_create.html.haml_spec.rb
  spec/views/mobile_phone/verify_token.html.haml_spec.rb
Labels: KYC, backend, cla-signed, enhancement, frontend

#136 separate SERVER_HOST from port so we can choose a cookie name correctly
  .env.example
  app/views/layouts/_cookie_consent.html.haml
  config/application.rb
Labels: GDPR, cla-signed

#139 Only allow login if swaps are open
  app/views/layouts/application.html.haml
Labels: KYC, Twitter, cla-signed, facebook, frontend

#128 promote greater transparency
  app/helpers/application_helper.rb
  app/views/static_pages/about.html.haml
  app/views/static_pages/faq.html.haml
Labels: cla-signed, easy, frontend, impact

#137 Update login button to new Facebook branding
  app/assets/images/facebook_icon.png
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/button.scss
  app/views/layouts/_login.html.haml
Labels: cla-signed

#133 Issue 8 add ons ids everywhere: preparation
  app/models/ons_constituency.rb
  db/fixtures/constituencies_original_with_ons_csv.rb
  db/fixtures/constituency_original_names_with_ons_ids.csv
  db/fixtures/ons_constituency_lookup.rb
  db/migrate/20191123112854_populate_ons_constituencies.rb
  db/migrate/20191123122549_add_ons_id_to_polls.rb
  db/migrate/20191123122646_add_ons_id_to_users.rb
  db/schema.rb
  lib/tasks/constituency_original.rake
Labels: cla-signed

#144 Minor tweaks to Facebook login button
  .scss-lint.yml
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/button.scss
Labels: cla-signed

#146 delete unused test/ hierarchy
  test/fixtures/ons_constituencies.yml
  test/models/ons_constituency_test.rb
Labels: backend, cla-signed, tech debt

#145 default to SERVER_HOST if SERVER_HOST_PORT is not set
  config/application.rb
Labels: backend, cla-signed, tech debt

#147 Update guard-scss_lint
  Gemfile.lock
Labels: cla-signed

#148 Use puma and auto-migrate on deploy
  Gemfile
  Gemfile.lock
  Procfile
Labels: backend, cla-signed, tech debt

#152 Improve CLA process
  .clabot
  README.md
Labels: cla-signed

#163 Add Travis CI notifications to Slack
  .travis.yml
Labels: cla-signed

#162 Add yarn and webpacker to Travis config
  .travis.yml
Labels: cla-signed

#94 request user_link permission from facebook (#48)
  config/initializers/omniauth.rb
Labels: KYC, backend, cla-signed, facebook

#167 Updates links in footer
  app/views/layouts/_footer.html.haml
Labels: cla-signed

#170 use guard-yarn to run yarn on package.json changes
  Gemfile
  Gemfile.lock
  Guardfile
Labels: cla-signed

#174 update Font Awesome (latest version of v4)
  app/views/layouts/application.html.haml
Labels: cla-signed

#169 Issue #159 welcome email
  app/models/sent_email.rb
  app/models/user.rb
  db/migrate/20191126222547_create_sent_emails.rb
  db/schema.rb
  spec/factories/sent_emails.rb
  spec/models/sent_email_spec.rb
  spec/models/user_spec.rb
Labels: cla-signed

#89 Social profiles
  app/controllers/sessions_controller.rb
  app/models/identity.rb
  app/models/user.rb
  db/migrate/20191125142930_create_identities.rb
  db/migrate/20191125151240_migrate_profile_data.rb
  db/migrate/20191127125417_remove_uid_image_provider_from_user.rb
  db/schema.rb
  db/seeds/development/users.seeds.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/identity.rb
  spec/factories/user.rb
  spec/fixtures/users.yml
  spec/models/user_spec.rb
  spec/requests/user/callbacks_spec.rb
  spec/views/mobile_phone/verify_create.html.haml_spec.rb
Labels: KYC, Twitter, backend, cla-signed, facebook

#177 Extract prepopulated code into separate method
  app/controllers/home_controller.rb
Labels: cla-signed, tech debt

#179 Fix webpack CSS for production sites
  app/views/users/edit.html.haml
Labels: cla-signed

#181 Store profile_url for facebook identities (#48)
  app/models/identity.rb
  db/migrate/20191127224254_add_profile_url_to_identity.rb
  db/schema.rb
  spec/requests/user/callbacks_spec.rb
Labels: cla-signed

#178 Issue #154 refresh polls data
  db/fixtures/electoral_calculus_constituencies.tsv
  db/fixtures/electoral_calculus_constituencies_tsv.rb
  db/migrate/20191126092838_add_brexit_party.rb
  db/migrate/20191126122621_refresh_polls.rb
  db/seeds.rb
Labels: cla-signed

#190 HTTPS links to prevent redirects
  app/views/user/swaps/_double_check_constituency.html.haml
Labels: cla-signed

#188 https link to https://www.electoralcalculus.co.uk/orderedseats.html
  app/views/user/swaps/_list_potential_swaps.html.haml
Labels: cla-signed

#189 HTTPS link to https://www.electoralcalculus.co.uk/orderedseats.html
  db/fixtures/README
Labels: cla-signed

#192 Handle absence of user profile URL better in UI
  app/controllers/user/swaps_controller.rb
  app/helpers/users_helper.rb
  app/mailers/user_mailer.rb
  app/models/identity.rb
  app/views/user_mailer/reminder_to_vote.html.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/users/show/_swap_confirmed.html.haml
  spec/helpers/user_helper_spec.rb
Labels: KYC, cla-signed, facebook, frontend

#180 Issue #125 swap expiry config
  app/helpers/swaps_helper.rb
  app/mailers/user_mailer.rb
  app/models/swap.rb
  app/views/static_pages/faq.html.haml
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/welcome_email.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
  lib/tasks/swaps.rake
  spec/factories/swaps.rb
  spec/helpers/swaps_helper_spec.rb
  spec/models/swap_spec.rb
Labels: cla-signed

#194 Dont show zero vote polls
  app/helpers/polls_helper.rb
  db/schema.rb
  spec/factories/polls.rb
  spec/helpers/polls_helper_spec.rb
Labels: cla-signed

#198 API: Allow prepopulation of constituency
  app/controllers/api_controller.rb
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/user/constituencies_controller.rb
  app/helpers/static_pages_helper.rb
  app/views/static_pages/api.html.haml
  app/views/user/constituencies/edit.html.haml
  spec/controllers/application_controller_spec.rb
  spec/controllers/user/constituencies_controller_spec.rb
  spec/factories/ons_constituency.rb
Labels: cla-signed

#207 Allow Facebook log in to be disabled
  app/helpers/application_helper.rb
  app/views/layouts/_login.html.haml
Labels: cla-signed

#205 Always load Google Analytics over HTTPS
  app/views/layouts/_google_analytics.html.haml
Labels: cla-signed, frontend, tech debt

#208 Clarify the matching process
  app/assets/stylesheets/home.scss
  app/views/static_pages/faq.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
Labels: cla-signed, easy, enhancement, frontend, swap options

#158 Test: users_controller.rb
  spec/controllers/users_controller_spec.rb
Labels: cla-signed, tech debt

#187 Enforce phone verification
  app/controllers/user/swaps_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/mobile_phone/_form.html.haml
  app/views/user/swaps/_searching_for_swap.html.haml
  app/views/user/swaps/show.html.haml
  app/views/users/edit.html.haml
  app/views/users/show.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
  spec/controllers/user/swaps_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: KYC, cla-signed, frontend, mobile verification

#212 meta tag updates
  app/views/layouts/application.html.haml
Labels: cla-signed, frontend

#210 Issue #6 postcode lookup
  app/javascript/packs/postcodesHelper.js
  app/views/user/constituencies/edit.html.haml
  app/views/users/_postcode_field.html.haml
  app/views/users/edit.html.haml
Labels: cla-signed

#214 Refactor social sharing buttons
  app/views/user/share/_social.html.haml
  app/views/user/share/show.html.haml
  app/views/user/swaps/_searching_for_swap.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
Labels: Twitter, cla-signed, easy, facebook, frontend, impact

#215 Add notion of test users
  .env.example
  app/controllers/user/swaps_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/models/user.rb
  app/views/user/swaps/_searching_for_swap.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
  config/environments/test.rb
  spec/controllers/user/swaps_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/user_spec.rb
Labels: cla-signed
