Repository swapmyvote/swapmyvote, pull requests merged in 2019-12, with the labels that each got.

#223 #34 #73 Copy changes and privacy policy
  app/views/layouts/_footer.html.haml
  app/views/static_pages/about.html.haml
  app/views/static_pages/contact.html.haml
  app/views/static_pages/faq.html.haml
  app/views/static_pages/privacy.html.haml
  app/views/static_pages/terms.html.haml
Labels: cla-signed

#227 Issue #161 show tactical recommendations
  .editorconfig
  app/assets/stylesheets/profile.scss
  app/views/recommendations/_recommendation.html.haml
  app/views/user/swaps/_list_potential_swaps.html.haml
  app/views/user/swaps/_swap_profile.html.haml
Labels: cla-signed

#149 Change information message when token is wrong
  app/controllers/mobile_phone_controller.rb
  app/services/swap_my_vote/message_bird.rb
  app/views/mobile_phone/verify_create.html.haml
Labels: cla-signed, duplicate, frontend, mobile verification

#239 Fix FAQ and test static page views
  Guardfile
  app/views/static_pages/faq.html.haml
  spec/views/static_pages/about_haml_spec.rb
  spec/views/static_pages/api_haml_spec.rb
  spec/views/static_pages/contact_haml_spec.rb
  spec/views/static_pages/cookies_haml_spec.rb
  spec/views/static_pages/faq_haml_spec.rb
  spec/views/static_pages/privacy_haml_spec.rb
  spec/views/static_pages/terms_haml_spec.rb
Labels: cla-signed

#228 Fix tests
  .prettierrc
  app/assets/stylesheets/home.scss
  config/environments/test.rb
  spec/controllers/user/constituencies_controller_spec.rb
  spec/controllers/user/swaps_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/ons_constituency.rb
  spec/factories/user.rb
  spec/helpers/user_helper_spec.rb
  spec/models/mobile_phone_spec.rb
  spec/models/user_spec.rb
  spec/views/mobile_phone/verify_create.html.haml_spec.rb
Labels: cla-signed

#237 Add consent checkbox to sign-up/in screen
  app/views/layouts/_login.html.haml
Labels: cla-signed

#253 Force users to have an email and guard against sending emails when missing
  app/controllers/user/swaps_controller.rb
  app/controllers/users_controller.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/user/constituencies/edit.html.haml
  spec/controllers/user/swaps_controller_spec.rb
Labels: cla-signed

#252 Only link to a new swap on the potential swaps page
  app/views/user/swaps/_list_potential_swaps.html.haml
  app/views/user/swaps/_swap_profile.html.haml
  app/views/user/swaps/_swap_profile_inner.html.haml
Labels: bug, cla-signed, frontend

#255 Refactor long User#swap_with_user_id method
  app/models/user.rb
Labels: cla-signed

#256 Use absolute path to partial
  app/views/user/swaps/_swap_profile.html.haml
Labels: cla-signed

#242 Issue #238 live from brexit data refresh
  db/fixtures/livefrombrexit_recommendations.json
  db/migrate/20191202081913_recommendations_refresh_dec01.rb
  db/schema.rb
  db/seeds.rb
Labels: cla-signed

#247 Improve UX of postcode input
  app/views/users/_postcode_field.html.haml
Labels: cla-signed, design, easy, frontend

#263 Cast image urls to protocol agnostic URLs
  app/models/user.rb
  spec/requests/user/callbacks_spec.rb
Labels: cla-signed

#240 Adding support to footer links in mailers
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/no_swap.haml
  app/views/user_mailer/not_swapped_follow_up.haml
  app/views/user_mailer/partner_has_voted.html.haml
  app/views/user_mailer/reminder_to_vote.html.haml
  app/views/user_mailer/swap_cancelled.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/user_mailer/swap_not_confirmed.html.haml
  app/views/user_mailer/welcome_email.html.haml
Labels: Email, cla-signed, impact

#264 adding some simple view specs
  spec/views/user/swaps/new.html.haml_spec.rb
  spec/views/user/swaps/show.html.haml_spec.rb
  spec/views/users/show.html.haml_spec.rb
Labels: cla-signed

#265 Merge from master plus BS tweaks
  app/assets/stylesheets/autocomplete.scss
  app/assets/stylesheets/bootstrap-forms.scss
  app/assets/stylesheets/modal.scss
  app/controllers/user/swaps_controller.rb
  app/controllers/users_controller.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/layouts/_login.html.haml
  app/views/mobile_phone/_form.html.haml
  app/views/user/constituencies/edit.html.haml
  app/views/user/share/_social.html.haml
  app/views/user/swaps/_list_potential_swaps.html.haml
  app/views/user/swaps/_swap_profile.html.haml
  app/views/user/swaps/_swap_profile_inner.html.haml
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/no_swap.haml
  app/views/user_mailer/not_swapped_follow_up.haml
  app/views/user_mailer/partner_has_voted.html.haml
  app/views/user_mailer/reminder_to_vote.html.haml
  app/views/user_mailer/swap_cancelled.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/user_mailer/swap_not_confirmed.html.haml
  app/views/user_mailer/welcome_email.html.haml
  app/views/users/_postcode_field.html.haml
  config/environments/production.rb
  db/fixtures/livefrombrexit_recommendations.json
  db/migrate/20191202081913_recommendations_refresh_dec01.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/user/swaps_controller_spec.rb
  spec/requests/user/callbacks_spec.rb
Labels: cla-signed

#286 Reintroduce linters to Travis
  .travis.yml
  app/models/user.rb
Labels: cla-signed

#268 Cancel swap no user
  .rubocop.yml
  Guardfile
  app/mailers/user_mailer.rb
  app/views/user_mailer/swap_cancelled.haml
  config/environments/test.rb
  spec/mailers/user_mailer_spec.rb
Labels: cla-signed

#289 Handle unspecified constituencies
  app/controllers/user/swaps_controller.rb
  app/models/user.rb
  app/views/user/swaps/_double_check_constituency.html.haml
  spec/controllers/user/swaps_controller_spec.rb
  spec/factories/user.rb
  spec/models/user_spec.rb
Labels: backend, bug, cla-signed

#290 Live from brexit data refresh dec 06
  app/assets/stylesheets/profile.scss
  app/models/recommendation.rb
  db/fixtures/livefrombrexit_recommendations.json
  db/migrate/20191206161508_recommendations_refresh_dec06.rb
  db/schema.rb
  db/seeds.rb
Labels: cla-signed

#291 Try to handle ActionController::InvalidAuthenticityToken better
  app/controllers/application_controller.rb
Labels: bug, cla-signed

#296 Merge from master
  .clabot
  .rubocop.yml
  .travis.yml
  Guardfile
  app/assets/stylesheets/profile.scss
  app/controllers/application_controller.rb
  app/controllers/mobile_phone_controller.rb
  app/controllers/user/swaps_controller.rb
  app/mailers/user_mailer.rb
  app/models/recommendation.rb
  app/models/user.rb
  app/views/user/swaps/_double_check_constituency.html.haml
  app/views/user_mailer/swap_cancelled.haml
  config/environments/test.rb
  db/fixtures/livefrombrexit_recommendations.json
  db/migrate/20191206161508_recommendations_refresh_dec06.rb
  db/schema.rb
  db/seeds.rb
  doc/db-schema.md
  doc/user-swap-schema.plantuml
  spec/controllers/user/swaps_controller_spec.rb
  spec/factories/user.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/user_spec.rb
  spec/views/user/swaps/new.html.haml_spec.rb
  spec/views/user/swaps/show.html.haml_spec.rb
  spec/views/users/show.html.haml_spec.rb
Labels: cla-signed

#287 Issue #277 Offer better swaps
  app/models/ons_constituency.rb
  app/models/poll.rb
  app/models/user.rb
  db/migrate/20191203223552_add_marginal_score_to_polls.rb
  db/migrate/20191205084216_calculate_marginal_score.rb
  db/migrate/20191206111031_add_indexes_for_finding_swaps.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/development/users.seeds.rb
  spec/models/poll_spec.rb
Labels: cla-signed

#293 Issue #229 recommendation site sort order
  app/helpers/recommendations_helper.rb
  app/views/user/swaps/_swap_profile.html.haml
  spec/helpers/recommendations_helper_spec.rb
Labels: cla-signed

#301 make more of consent and login text viewable on mobile (#257)
  app/assets/stylesheets/modal.scss
Labels: cla-signed

#300 improves layout a bit for long recommendation text (#232)
  app/assets/stylesheets/profile.scss
Labels: cla-signed

#310 Issue #277 sort marginals to top
  app/models/user.rb
Labels: cla-signed

#312 Issue #311 recommendations refresh
  app/models/recommendation.rb
  db/fixtures/livefrombrexit_recommendations.json
  db/fixtures/livefrombrexit_recommendations_json.rb
  db/migrate/20191208113028_recommendations_refresh_dec08.rb
  db/schema.rb
Labels: cla-signed

#331 Add more people to FAQ page
  app/views/static_pages/faq.html.haml
Labels: CLA-signed

#329 Scrollable modals
  app/assets/javascripts/autocomplete.js
  app/assets/javascripts/modal.coffee
  app/assets/stylesheets/modal.scss
  app/views/home/_swaps_open.html.haml
  app/views/layouts/_login.html.haml
  app/views/layouts/application.html.haml
  app/views/static_pages/faq.html.haml
  app/views/users/edit.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
Labels: CLA-signed

#325 Verification icons
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/profile.scss
  app/views/user/swaps/_swap_profile_inner.html.haml
Labels: CLA-signed

#322 Issue #230 apply party colours to recommendations
  app/models/party.rb
  app/models/recommendation.rb
  app/views/recommendations/_recommendation.html.haml
  spec/factories/parties.rb
  spec/models/party_spec.rb
  spec/models/recommendation_spec.rb
  spec/views/user/swaps/show.html.haml_spec.rb
Labels: CLA-signed

#333 Fix crashes when authentication fails
  app/controllers/users/omniauth_callbacks_controller.rb
  app/helpers/application_helper.rb
  app/views/layouts/_login.html.haml
  config/initializers/devise.rb
Labels: CLA-signed

#340 Add view spec for login modal dialog
  Gemfile
  Gemfile.lock
  app/views/layouts/_login.html.haml
  spec/views/layouts/_login.html.haml_spec.rb
Labels: CLA-signed, tech debt

#334 Issue #324 share email address
  app/controllers/user/swaps_controller.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/user/swaps/new.html.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
  app/views/users/show/_swap_confirmed.html.haml
  db/migrate/20191209132125_add_consent_share_email_to_swaps.rb
  db/schema.rb
  spec/controllers/users_controller_spec.rb
  spec/helpers/user_helper_spec.rb
  spec/models/user_spec.rb
  spec/views/user_mailer/swap_confirmed.html.haml_spec.rb
Labels: CLA-signed

#323 Dynamic mobile number verification
  app/controllers/mobile_phone_controller.rb
Labels: CLA-signed

#344 Tweak FAQ
  app/views/static_pages/faq.html.haml
Labels: CLA-signed, copy, easy

#355 Issue #337 retrospective email consent
  app/controllers/user/swaps_controller.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/user_mailer/email_address_shared.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
  app/views/users/show/_swap_confirmed.html.haml
  spec/controllers/user/swaps_controller_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/user_spec.rb
Labels: CLA-signed

#354 redirect straight to swap page when there are swaps available
  app/controllers/user/constituencies_controller.rb
  spec/controllers/user/constituencies_controller_spec.rb
Labels: CLA-signed

#358 Improve email address validation behaviour
  app/models/user.rb
  spec/models/user_spec.rb
Labels: CLA-signed

#363 Issue #361 voting open
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/views/home/_voting_open.html.haml
  app/views/home/index.html.haml
  spec/controllers/user/constituencies_controller_spec.rb
  spec/helpers/application_helper_spec.rb
Labels: CLA-signed

#364 add polling station link
  app/views/home/_voting_open.html.haml
Labels: CLA-signed

#359 Give helpful next steps if email already exists at login
  app/models/concerns/user_errors_concern.rb
  app/models/user.rb
Labels: CLA-signed, email, enhancement, frontend, impact, timesensitive

#365 fix email address shared method
  app/mailers/user_mailer.rb
Labels: CLA-signed

#366 #362 really simple restriction to prevent confirmed swappers from changing…
  app/controllers/users_controller.rb
Labels: CLA-signed

#367 collapse SWAPS_CLOSED and VOTING_OPEN into SWAPMYVOTE_MODE
  .env.example
  COMMANDS.md
  app/controllers/application_controller.rb
  app/controllers/concerns/app_mode_concern.rb
  app/controllers/home_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/mailers/user_mailer.rb
  app/views/home/_voting_open.html.haml
  app/views/home/index.html.haml
  app/views/shared/_go_vote.html.haml
  app/views/shared/_reach_out_to_swap.html.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/users/_info_summary.html.haml
  app/views/users/edit.html.haml
  app/views/users/show/_swap_confirmed.html.haml
  config/environments/test.rb
  spec/controllers/home_controller_spec.rb
  spec/controllers/user/constituencies_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/requests/user/constituencies_spec.rb
  spec/support/swaps_closed.rb
Labels: CLA-signed

#370 fix for failed confirm swap mail #368
  app/mailers/user_mailer.rb
Labels: CLA-signed

#373 Add Andy's bio to the FAQ
  app/views/static_pages/faq.html.haml
Labels: CLA-signed

#375 Wind down mode
  app/controllers/mobile_phone_controller.rb
  app/controllers/users_controller.rb
  app/views/home/_closed_warm_up.html.haml
  app/views/home/_closed_wind_down.html.haml
  app/views/home/index.html.haml
Labels: CLA-signed, copy, frontend, timesensitive

#380 Simple copy changes
  app/views/home/_closed_wind_down.html.haml
  app/views/static_pages/privacy.html.haml
Labels: CLA-signed
