Repository swapmyvote/swapmyvote, pull requests merged in 2021-06, with the labels that each got.

#439 Be2021 google doc as yaml
  app/helpers/application_helper.rb
  app/models/party.rb
  app/views/static_pages/api.html.haml
  db/fixtures/be2021.yml
  db/fixtures/be2021/candidate.rb
  db/fixtures/be2021/party.rb
  db/fixtures/be2021_yaml.rb
  db/seeds.rb
  db/seeds/development/users.seeds.rb
  db/seeds_for_general_election.rb
  spec/db/fixtures/be2021/candidate_spec.rb
  spec/db/fixtures/be2021/party_spec.rb
  spec/db/fixtures/be2021_yaml_spec.rb
  spec/models/party_spec.rb
Labels: BE2021, CLA-signed

#446 Simplify BE2021 fixtures to only use class methods
  Guardfile
  db/fixtures/be2021/candidate.rb
  db/fixtures/be2021/party.rb
  db/fixtures/be2021_yaml.rb
  spec/db/fixtures/be2021/candidate_spec.rb
  spec/db/fixtures/be2021/party_spec.rb
  spec/db/fixtures/be2021_yaml_spec.rb
Labels: BE2021, CLA-signed, easy, tech debt

#447 Remove tactical recommendations BE21ONLY
  app/views/user/swaps/_swap_profile.html.haml
Labels: BE2021, CLA-signed

#450 Fix whitespace style issues in user_mailer templates
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/not_swapped_follow_up.haml
  app/views/user_mailer/welcome_email.html.haml
Labels: CLA-signed, easy, tech debt

#457 Clear postcode when constituency is changed
  app/assets/javascripts/autocomplete.js
Labels: BE2021, CLA-signed, easy, frontend, javascript

#451 Validate constituency from postcode input
  app/javascript/packs/postcodesHelper.js
Labels: CLA-signed, easy, frontend, javascript

#463 Keep only parties in both constituencies
  app/views/static_pages/api.html.haml
  db/fixtures/be2021.yml
  spec/models/party_spec.rb
Labels: BE2021, CLA-signed

#464 do not allow swaps in same constituency
  app/models/user.rb
  spec/models/user_spec.rb
Labels: BE2021, CLA-signed

#224 Redacting political affilliations from mails
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/no_swap.haml
  app/views/user_mailer/not_swapped_follow_up.haml
  app/views/user_mailer/partner_has_voted.html.haml
  app/views/user_mailer/reminder_to_vote.html.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/user_mailer/swap_not_confirmed.html.haml
Labels: CLA-signed, copy

#455 Swap prevention with same party
  app/controllers/users_controller.rb
  app/models/concerns/distinct_parties_validator.rb
  app/models/user.rb
  app/views/home/_swaps_open.html.haml
  app/views/static_pages/faq.html.haml
  spec/controllers/users_controller_spec.rb
  spec/models/user_spec.rb
Labels: CLA-signed

#468 Remove links to GE2019 crowdfunder
  app/views/layouts/_footer.html.haml
  app/views/layouts/application.html.haml
Labels: BE2021, CLA-signed, frontend, impact, timesensitive

#471 BE21ONLY Use BE2021 facebook sharing banner from Josh and update meta tags
  app/assets/images/facebook_sharing_banner_BE2021.jpg
  app/views/layouts/application.html.haml
Labels: BE2021, CLA-signed, copy, frontend, impact

#472 BE2021 fix FAQ regarding Twitter/Facebook contact methods
  app/views/static_pages/faq.html.haml
Labels: BE2021, CLA-signed, copy, frontend

#475 Remove app_id parameter in fb sharer.php links
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/email_address_shared.html.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/user_mailer/welcome_email.html.haml
Labels: BE2021, CLA-signed, Facebook, frontend, impact

#470 Update show.html.haml
  app/views/user/vote/show.html.haml
Labels: BE2021, copy, frontend

#477 BE2021 Fix tweets in mails to use #byelection etc.
  app/helpers/application_helper.rb
  app/views/user/vote/show.html.haml
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/email_address_shared.html.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/user_mailer/welcome_email.html.haml
Labels: BE2021, CLA-signed, impact

#482 Add admin interface for forcing mobile number verification without SMS
  app/controllers/admin_controller.rb
  app/views/admin/verify_mobile.html.haml
  config/routes.rb
Labels: CLA-signed, backend, enhancement, frontend, mobile verification

#486 Modal fix
  app/views/layouts/_login.html.haml
Labels: CLA-signed
