Repository swapmyvote/swapmyvote, pull requests merged in 2022-06, with the labels that each got.

#542 2022 copy updates
  app/assets/images/facebook_sharing_banner_BE2022.jpg
  app/assets/images/facebook_sharing_banner_BE2022.png
  app/helpers/application_helper.rb
  app/views/home/_closed_warm_up.html.haml
  app/views/home/_closed_wind_down.html.haml
  app/views/home/_open_and_voting.html.haml
  app/views/home/_open_pre_elections.html.haml
  app/views/layouts/application.html.haml
  app/views/static_pages/faq.html.haml
  app/views/user/vote/show.html.haml
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/email_address_shared.html.haml
  app/views/user_mailer/no_swap.haml
  app/views/user_mailer/reminder_to_vote.html.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/user_mailer/swap_not_confirmed.html.haml
  app/views/user_mailer/welcome_email.html.haml
Labels: CLA-signed

#545 Rubocop hound update
  .haml.yml
  .hound.yml
  Gemfile
  Gemfile.lock
Labels: CLA-signed

#543 issue 347 proof read emails
  app/controllers/admin_controller.rb
  app/views/admin/index.html.haml
  config/routes.rb
  spec/controllers/admin_controller_spec.rb
Labels: CLA-signed

#555 improve cookies message for mobile users #554
  app/views/layouts/_cookie_consent.html.haml
Labels: frontend, CLA-signed, BE2022

#549 haml lint
  .haml-lint.yml
  .haml-lint_todo.yml
  .hound.yml
  Gemfile
  Gemfile.lock
  Guardfile
  Rakefile
  app/views/static_pages/api.html.haml
  app/views/static_pages/faq.html.haml
  app/views/static_pages/privacy.html.haml
  app/views/static_pages/terms.html.haml
Labels: tech debt, CLA-signed, comms

#550 visual tweaks
  app/views/user/swaps/new.html.haml
  app/views/users/edit.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
  app/views/users/show/_swap_confirmed.html.haml
Labels: CLA-signed, BE2022

#553 Homepage text
  app/views/home/_open_and_voting.html.haml
Labels: CLA-signed, copy, BE2022

#562 fix validation errors in app.json
  app.json
Labels: CLA-signed

#560 action network form embed partial
  app/views/home/_actionnetwork.html
  app/views/home/_closed_warm_up.html.haml
  app/views/home/_closed_wind_down.html.haml
Labels: impact, easy, CLA-signed, BE2022, mailing list

#563 conditionally display FAQ entries based on Twitter/Facebook support
  app/views/static_pages/faq.html.haml
Labels: CLA-signed

#567 action network form styling
  app/views/home/_actionnetwork.html
Labels: CLA-signed, email, comms, BE2022

#569 action network form centered in page
  app/views/home/_actionnetwork.html
Labels: CLA-signed

#572 update pry-coolline to 0.2.6 to avoid warning
  Gemfile.lock
Labels: CLA-signed

#548 Issue 444 hide polls when two only constituencies
  .haml-lint_todo.yml
  app/controllers/user/swaps_controller.rb
  app/controllers/users_controller.rb
  app/views/user/swaps/_double_check_constituency.html.haml
  app/views/user/swaps/_list_potential_swaps.html.haml
  app/views/user/swaps/_swap_profile.html.haml
  app/views/user/swaps/_swap_profile_inner.html.haml
  app/views/user/swaps/new.html.haml
  app/views/user/swaps/show.html.haml
  app/views/users/show.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
  app/views/users/show/_swap_confirmed.html.haml
  spec/controllers/user/swaps_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/views/user/swaps/new.html.haml_spec.rb
Labels: CLA-signed, BE2022

#571 record user's consent to be sent newsletters (#195)
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users_controller.rb
  app/views/devise/registrations/new.html.erb
  db/migrate/20220607065010_add_news_email_consent_to_user.rb
  db/schema.rb
Labels: GDPR, CLA-signed, email, comms, ruby, BE2022, mailing list

#574 fix @SwapMyVote and URL appearing twice in twitter message
  app/helpers/application_helper.rb
Labels: bug, Twitter, CLA-signed, ruby, BE2022

#597 add GitHub action
  .github/workflows/rubyonrails.yml
  .haml-lint.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: CLA-signed

#592 Copy review pt1
  app/views/home/_closed_and_voting.html.haml
  app/views/home/_closed_wind_down.html.haml
  app/views/home/_open_pre_elections.html.haml
  app/views/home/_swap_form.html.haml
  app/views/static_pages/faq.html.haml
Labels: frontend, CLA-signed, copy, comms

#589 action-network-form-width-fix
  app/views/home/_actionnetwork.html
Labels: CLA-signed

#603 update app.json to skip deploying add-ons for review apps
  app.json
Labels: CLA-signed

#601 Issue 573 reinstate donate
  app/helpers/application_helper.rb
  app/views/home/_closed_wind_down.html.haml
  app/views/layouts/_donate.html.haml
  app/views/layouts/_footer.html.haml
  app/views/layouts/application.html.haml
  app/views/user_mailer/_footer_fixed_links.html.haml
  app/views/user_mailer/confirm_swap.html.haml
  app/views/user_mailer/email_address_shared.html.haml
  app/views/user_mailer/no_swap.haml
  app/views/user_mailer/not_swapped_follow_up.haml
  app/views/user_mailer/partner_has_voted.html.haml
  app/views/user_mailer/reminder_to_vote.html.haml
  app/views/user_mailer/swap_cancelled.haml
  app/views/user_mailer/swap_confirmed.html.haml
  app/views/user_mailer/swap_not_confirmed.html.haml
  app/views/user_mailer/welcome_email.html.haml
Labels: CLA-signed, comms, BE2022

#599 update webpacker to 5.4.3
  Gemfile
  Gemfile.lock
  babel.config.js
  config/webpacker.yml
  package.json
  yarn.lock
Labels: frontend, tech debt, CLA-signed, security

#600 issue 594 my email consent confusion
  app/helpers/users_helper.rb
  app/models/user.rb
  app/views/users/show/_confirm_outgoing_swap.html.haml
  app/views/users/show/_swap_confirmed.html.haml
  doc/analysis_for_issue_594.md
  spec/models/user_spec.rb
Labels: tech debt, CLA-signed, ruby, BE2022

#602 only shrink width of profile-content if polls are shown
  app/assets/stylesheets/profile.scss
  app/controllers/user/swaps_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/views/home/_swap_form.html.haml
  app/views/user/swaps/_double_check_constituency.html.haml
  app/views/user/swaps/_list_potential_swaps.html.haml
  app/views/user/swaps/_swap_profile.html.haml
  app/views/user/swaps/_swap_profile_inner.html.haml
  app/views/user/swaps/new.html.haml
  app/views/user/swaps/show.html.haml
  app/views/users/show.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
  app/views/users/show/_swap_confirmed.html.haml
Labels: frontend, design, CLA-signed, BE2022

#596 issue 584 email consent mandatory
  .haml-lint_todo.yml
  app/controllers/user/swaps_controller.rb
  app/models/user.rb
  app/views/user/swaps/new.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
  spec/controllers/user/swaps_controller_spec.rb
  spec/models/user_spec.rb
Labels: frontend, GDPR, CLA-signed, email, ruby, BE2022

#614 issue 613 api docs quick fix
  app/views/static_pages/api.html.haml
Labels: CLA-signed, comms, API, BE2022

#631 issue 335 share by email prompt mailto
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/button.scss
  app/assets/stylesheets/profile.scss
  app/views/user/share/_social.html.haml
Labels: frontend, CLA-signed, email, comms, javascript

#633 close off the route to empty constituencies via user/constituencies/edit (#622)
  app/controllers/user/constituencies_controller.rb
  spec/controllers/user/constituencies_controller_spec.rb
Labels: bug, frontend, CLA-signed, ruby, constituencies, BE2022, integrity

#630 issue 557 non voting users signup part 2
  app/views/home/_closed_and_voting.html.haml
  app/views/home/_news_sign_up_before_polls_close.html.haml
  app/views/home/_open_and_voting.html.haml
  app/views/home/_open_pre_elections.html.haml
Labels: CLA-signed, email, comms, mailing list
