Repository swapmyvote/swapmyvote, pull requests merged in 2024-06, with the labels that each got.

#762 fix electoral calculus matching
  db/fixtures/electoral_calculus_constituency_mapping_to_mysoc.yml
  db/fixtures/electoral_calculus_polls_raw.rb
  db/fixtures/electoral_commission_parties.rb
Labels: CLA-signed, ruby, constituencies, parties, GE2024, boundary-changes

#768 integrate tactical dot vote
  db/fixtures/tactical_vote_tacticalvote.csv
  db/fixtures/tactical_vote_tacticalvote_csv.rb
  db/fixtures/tactical_vote_tacticalvote_recs.rb
  db/seeds_for_general_election.rb
Labels: CLA-signed, ruby, constituencies, parties, GE2024

#776 correct ONS code for York Outer
  app/views/static_pages/api.html.haml
  spec/views/static_pages/__snapshots__/api_by_election.snap
  spec/views/static_pages/__snapshots__/api_general.snap
Labels: CLA-signed, API, constituencies, GE2024

#777 issue 763 test database setup
  README.md
  app/views/static_pages/about.html.haml
Labels: CLA-signed, GE2024

#779 Allow building on an ARM Mac
  Gemfile.lock
  package.json
Labels: CLA-signed

#767 tell user they need to verify mobile number
  app/controllers/users_controller.rb
  config/environments/development.rb
Labels: frontend, CLA-signed, mobile verification, rails action /user/edit, GE2024, UX

#784 Fix "envirobment" typos
  doc/new_election/by_election_data_coding_tasks.md
  doc/new_election/general_election_data_coding_tasks.md
Labels: CLA-signed

#788 add `ELECTION_DATE` and `ELECTION_TYPE` to `.env.example`
  .env.example
Labels: tech debt, CLA-signed

#799 issue 794 party colours in poll chart
  app/models/party.rb
  db/seeds_for_general_election.rb
Labels: bug, CLA-signed, parties, GE2024

#789 remove erroneous `source:` options in `has_many`
  app/models/ons_constituency.rb
  app/models/party.rb
Labels: CLA-signed

#786 Improve UI consistency
  app/assets/stylesheets/home.scss
  app/assets/stylesheets/profile.scss
  app/javascript/packs/postcodesHelper.js
  app/models/concerns/user_errors_concern.rb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/layouts/_login.html.haml
  app/views/layouts/application.html.haml
  app/views/mobile_phone/verify_create.html.haml
  app/views/user/swaps/_list_potential_swaps.html.haml
  app/views/users/_postcode_field.html.haml
  app/views/users/edit.html.haml
  app/views/users/show/_confirm_outgoing_swap.html.haml
  package.json
  spec/views/layouts/__snapshots__/application_by_election.snap
  spec/views/layouts/__snapshots__/application_general.snap
  yarn.lock
Labels: CLA-signed

#791 issue 773 show aligned tv sites
  app/helpers/recommendations_helper.rb
  app/models/recommendation.rb
  app/views/recommendations/_party_recommendation.html.haml
  app/views/user/swaps/_swap_profile.html.haml
  db/fixtures/tactical_vote_sprintforpr_csv.rb
  db/fixtures/tactical_vote_sprintforpr_recs.rb
  db/fixtures/tactical_vote_stt_csv.rb
  db/fixtures/tactical_vote_stt_recs.rb
  db/fixtures/tactical_vote_tacticalvote_csv.rb
  db/fixtures/tactical_vote_tacticalvote_recs.rb
  doc/recommendations_import.md
  spec/helpers/recommendations_helper_spec.rb
  spec/views/user/swaps/show.html.haml_spec.rb
Labels: frontend, swap options, CLA-signed, ruby, GE2024

#810 update README
  README.md
Labels: CLA-signed

#801 issue 800 bug in user seeding
  db/seeds/development/users.seeds.rb
Labels: bug, CLA-signed, ruby, GE2024

#806 issue 805 api parties
  app/models/party.rb
  app/views/static_pages/api.html.haml
  db/seeds/development/users.seeds.rb
  spec/models/party_spec.rb
  spec/views/static_pages/__snapshots__/api_by_election.snap
  spec/views/static_pages/__snapshots__/api_general.snap
Labels: CLA-signed, API, GE2024

#807 integrate siu tv recs
  app/helpers/recommendations_helper.rb
  db/fixtures/tactical_vote_siu.csv
  db/fixtures/tactical_vote_siu_csv.rb
  db/fixtures/tactical_vote_siu_recs.rb
  db/seeds_for_general_election.rb
Labels: backend, CLA-signed, ruby, constituencies, parties, campaigner, GE2024

#808 Add a "Swap My Vote" button to swap cards
  app/assets/stylesheets/profile.scss
  app/views/user/swaps/_swap_profile.html.haml
  app/views/user/swaps/_swap_profile_inner.html.haml
  spec/views/layouts/__snapshots__/application_by_election.snap
  spec/views/layouts/__snapshots__/application_general.snap
Labels: CLA-signed

#790 Upgrade to Rails 6.1.7.8 and Ruby 3.3.2
  .env.test.example
  .github/workflows/rubyonrails.yml
  .rubocop.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  app/views/home/_closed_warm_up.html.haml
  app/views/home/_closed_wind_down.html.haml
  app/views/home/_news_sign_up_before_polls_close.html.haml
  app/views/recommendations/_party_recommendation.html.haml
  app/views/user/swaps/_list_potential_swaps.html.haml
  app/views/user/swaps/_swap_profile.html.haml
  app/views/user/swaps/show.html.haml
  app/views/users/_why_need_email.html.haml
  app/views/users/edit.html.haml
  bin/rails
  bin/rake
  bin/setup
  bin/spring
  bin/yarn
  config.ru
  config/application.rb
  config/cable.yml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/new_framework_defaults_6_1.rb
  config/initializers/permissions_policy.rb
  config/locales/en.yml
  config/spring.rb
  db/migrate/20240609223702_add_service_name_to_active_storage_blobs.active_storage.rb
  db/migrate/20240609223703_create_active_storage_variant_records.active_storage.rb
  db/migrate/20240616095034_add_index_polls.rb
  db/migrate/20240616103101_add_index_recommendation_constituency.rb
  db/migrate/20240616111118_add_index_recommended_party.rb
  db/schema.rb
  spec/controllers/admin_controller_spec.rb
  spec/db/fixtures/be2021/candidate_spec.rb
  spec/db/fixtures/be2021/party_spec.rb
  spec/db/fixtures/be2021_yaml_spec.rb
  spec/db/fixtures/be2022/candidate_spec.rb
  spec/db/fixtures/be2022/party_spec.rb
  spec/db/fixtures/be2022_yaml_spec.rb
  spec/db/fixtures/electoral_commission_parties_spec.rb
  spec/views/layouts/__snapshots__/application_by_election.snap
  spec/views/layouts/__snapshots__/application_general.snap
Labels: CLA-signed

#818 upgrade to node 16 and yarn 3
  .gitignore
  .nvmrc
  .yarn/releases/yarn-3.8.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: CLA-signed

#815 issue 814 aggregate mrp
  app/models/poll.rb
  app/views/user/swaps/_double_check_constituency.html.haml
  app/views/user/swaps/_list_potential_swaps.html.haml
  db/fixtures/mrp_averages.csv
  db/fixtures/mrp_averages_csv.rb
  db/fixtures/mrp_averages_polls.rb
  db/fixtures/mrp_averages_polls_raw.rb
  db/seeds_for_general_election.rb
Labels: backend, CLA-signed, ruby, constituencies, parties, GE2024

#822 issue 809 tacticalvote co uk
  app/helpers/recommendations_helper.rb
  db/fixtures/tactical_vote_tacticalvote_co_uk.json
  db/fixtures/tactical_vote_tacticalvote_co_uk_recs.rb
  db/seeds_for_general_election.rb
Labels: CLA-signed, constituencies, parties, campaigner, GE2024

#804 issue 797 fix password required
  app/models/user.rb
  spec/factories/user.rb
  spec/requests/user/callbacks_spec.rb
Labels: Facebook, Twitter, CLA-signed, security, rails action /user/edit, GE2024, UX

#823 issue 817 getvoting org
  app/helpers/recommendations_helper.rb
  db/fixtures/tactical_vote_getvoting.csv
  db/fixtures/tactical_vote_getvoting_csv.rb
  db/fixtures/tactical_vote_getvoting_recs.rb
  db/seeds_for_general_election.rb
Labels: CLA-signed, constituencies, parties, campaigner, GE2024

#828 disable logins during `closed-warm-up` mode
  app/controllers/application_controller.rb
  app/controllers/concerns/app_mode_concern.rb
  app/controllers/users/sessions_controller.rb
  app/views/layouts/application.html.haml
Labels: CLA-signed

#827 don't hardcode hostname into privacy link URL
  app/views/static_pages/faq.html.haml
Labels: CLA-signed

#829 upsert all rows of some seed tables in one go
  app/models/user.rb
  db/fixtures/mrp_averages_polls.rb
  db/fixtures/mysociety_constituencies_csv.rb
  db/seeds_for_general_election.rb
Labels: CLA-signed

#837 app.json: update stack to `heroku-22`
  app.json
Labels: CLA-signed

#832 environments/development: reintroduce debug log_level to config
  config/environments/development.rb
Labels: CLA-signed

#843 update admin guide and db maintenance queries
  db/maintenance/anonymise-users.sql
  db/maintenance/purge-tables.psql
  db/maintenance/recreate-users.sql
  doc/admin-guide.md
Labels: CLA-signed

#835 FAQ: update copy relating to by-elections
  app/views/static_pages/faq.html.haml
Labels: CLA-signed

#847 document the need to copy test environment example
  README.md
Labels: CLA-signed, GE2024

#849 add simply formatted imprint to footer
  app/assets/stylesheets/footer.scss
  app/views/layouts/_footer.html.haml
  spec/views/layouts/__snapshots__/application_by_election.snap
  spec/views/layouts/__snapshots__/application_general.snap
Labels: CLA-signed, GE2024

#848 set default env variables correctly for user seeding
  .env.example
Labels: CLA-signed, GE2024

#851 issue 229 tactical campaign names
  app/helpers/recommendations_helper.rb
  app/views/recommendations/_party_recommendation.html.haml
Labels: CLA-signed, campaigner, GE2024

#853 Add party labels to prediction chart
  app/assets/javascripts/polls.coffee
  app/helpers/polls_helper.rb
  app/models/party.rb
  spec/helpers/polls_helper_spec.rb
  spec/views/layouts/__snapshots__/application_by_election.snap
  spec/views/layouts/__snapshots__/application_general.snap
Labels: CLA-signed

#863 tweak TV campaign list
  app/helpers/recommendations_helper.rb
Labels: CLA-signed

#864 use primary buttons for choosing a swap
  app/views/user/swaps/_swap_profile.html.haml
Labels: CLA-signed

#862 Improve test user seeding
  app/models/user.rb
  db/seeds/development/users.seeds.rb
Labels: CLA-signed

#860 issue 816 3-way polling advice text
  app/models/poll.rb
  app/views/user/swaps/_polls_advice.html.haml
  app/views/user/swaps/_swap_profile.html.haml
  spec/models/poll_spec.rb
  spec/views/user/swaps/new.html.haml_spec.rb
  spec/views/user/swaps/show.html.haml_spec.rb
Labels: CLA-signed, campaigner, GE2024

#870 issue 867 tv import update stt
  db/fixtures/tactical_vote_stt_20240625_2058.csv
  db/fixtures/tactical_vote_stt_csv.rb
  spec/models/poll_spec.rb
Labels: CLA-signed, campaigner, GE2024

#881 Migrate to GA4
  app/views/layouts/_google_analytics.html.haml
Labels: CLA-signed

#879 issue-878: dont allow 9.7 to show in floating point
  app/views/user/swaps/_polls_advice.html.haml
Labels: bug, CLA-signed, GE2024

#883 remove broken link from SMS template
  app/controllers/mobile_phone_controller.rb
Labels: CLA-signed

#888 Fix profile image placement on Firefox
  app/views/user/swaps/_swap_profile.html.haml
Labels: CLA-signed

#889 Change "log in" to "log in or sign up"
  app/views/layouts/_login.html.haml
  spec/views/layouts/_login.html.haml_spec.rb
Labels: CLA-signed

#890 issue 875 tv import update tacticalvote
  db/fixtures/tactical_vote_tacticalvote.csv
  db/fixtures/tactical_vote_tacticalvote_csv.rb
  db/fixtures/tactical_vote_tacticalvote_recs.rb
Labels: CLA-signed, constituencies, parties, campaigner, GE2024

#895 Add an invisible CAPTCHA
  Gemfile
  Gemfile.lock
  app/controllers/users/registrations_controller.rb
  app/views/devise/registrations/new.html.erb
Labels: CLA-signed

#894 update docs for new election cycle
  doc/admin-guide.md
  doc/new_election/general_election_data_coding_tasks.md
Labels: CLA-signed

#904 issue 903 tv import vote climate
  app/helpers/recommendations_helper.rb
  db/fixtures/tactical_vote_voteclimate_29jun24.csv
  db/fixtures/tactical_vote_voteclimate_csv.rb
  db/fixtures/tactical_vote_voteclimate_recs.rb
  db/seeds_for_general_election.rb
Labels: CLA-signed, constituencies, parties, campaigner, GE2024

#917 tv updates jun29
  db/fixtures/tactical_vote_siu.csv
  db/fixtures/tactical_vote_sprintforpr.csv
Labels: CLA-signed, constituencies, parties, campaigner, GE2024

#893 Reinstate pageview
  app/views/layouts/_google_analytics.html.haml
Labels: CLA-signed
