Repository swapmyvote/swapmyvote, pull requests merged in 2024-07, with the labels that each got.

#897 Improve sign-up flow
  app/assets/stylesheets/home.scss
  app/controllers/users/registrations_controller.rb
  app/helpers/application_helper.rb
  app/models/user.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/home/_swap_form.html.haml
  app/views/layouts/_login.html.haml
  spec/spec_helper.rb
  spec/views/home/__snapshots__/_open_and_voting_by_election.snap
  spec/views/home/__snapshots__/_open_and_voting_general.snap
  spec/views/home/__snapshots__/_open_pre_elections_by_election.snap
  spec/views/home/__snapshots__/_open_pre_elections_general.snap
  spec/views/layouts/__snapshots__/application_by_election.snap
  spec/views/layouts/__snapshots__/application_general.snap
  spec/views/layouts/_login.html.haml_spec.rb
Labels: CLA-signed

#920 a gentler introduction to swap matching
  app/views/home/_open_pre_elections.html.haml
  app/views/home/_swap_form.html.haml
  spec/views/home/__snapshots__/_open_and_voting.snap
  spec/views/home/__snapshots__/_open_and_voting_by_election.snap
  spec/views/home/__snapshots__/_open_and_voting_general.snap
  spec/views/home/__snapshots__/_open_pre_elections_by_election.snap
  spec/views/home/__snapshots__/_open_pre_elections_general.snap
Labels: frontend, CLA-signed, GE2024

#926 remove mention of by-election in swap_confirmed email
  app/views/user_mailer/swap_confirmed.html.haml
  spec/views/user_mailer/__snapshots__/swap_confirmed.snap
Labels: CLA-signed

#927 clarify that a mobile phone number is required (to support SMS)
  app/views/admin/verify_mobile.html.haml
  app/views/mobile_phone/_form.html.haml
  app/views/mobile_phone/verify_create.html.haml
  app/views/users/edit.html.haml
  app/views/users/show/_confirm_incoming_swap.html.haml
Labels: CLA-signed

#936 clarify that user needs to click the Verify button
  app/controllers/users_controller.rb
Labels: CLA-signed

#937 improve /faq and /contact regarding support queries
  app/views/static_pages/contact.html.haml
  app/views/static_pages/faq.html.haml
Labels: CLA-signed

#941 Make Devise mails include names in sender and body
  app/mailers/application_mailer.rb
  app/mailers/user_mailer.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/static_pages/faq.html.haml
  config/initializers/devise.rb
Labels: CLA-signed

#885 tweak copy on swaps page
  app/views/user/swaps/_swap_profile.html.haml
Labels: CLA-signed

#838 seed Heroku review apps with a copy of the staging DB
  app.json
  db/migrate/20191123112854_populate_ons_constituencies.rb
  db/migrate/20191125100635_populate_recommendations.rb
  db/migrate/20191126092838_add_brexit_party.rb
  db/migrate/20191202081913_recommendations_refresh_dec01.rb
  db/migrate/20191206161508_recommendations_refresh_dec06.rb
  db/migrate/20191208113028_recommendations_refresh_dec08.rb
  db/schema.rb
Labels: CLA-signed

#945 fix test broken by introduction of `add_foreign_key` to `schema.rb`
  spec/models/user_spec.rb
Labels: CLA-signed

#919 issue 905 willing profile
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/user/swaps/_polls_interpretation.html.haml
  app/views/user/swaps/_polls_interpretation_self.html.haml
  app/views/user/swaps/_swap_profile.html.haml
  app/views/users/review.haml
  config/routes.rb
  spec/controllers/users_controller_spec.rb
  spec/models/user_spec.rb
Labels: frontend, CLA-signed, ruby, GE2024

#943 Improve contrast for links and subdued text
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/footer.scss
  app/assets/stylesheets/home.scss
  app/views/layouts/_current_user.html.haml
  app/views/layouts/_login.html.haml
  spec/views/layouts/__snapshots__/application_by_election.snap
  spec/views/layouts/__snapshots__/application_general.snap
Labels: CLA-signed

#944 Improve mobile phone verification flow
  app/controllers/user/swaps_controller.rb
  app/controllers/users_controller.rb
  app/views/mobile_phone/_form.html.haml
  app/views/mobile_phone/verify_create.html.haml
  app/views/user/constituencies/edit.html.haml
  app/views/users/_postcode_field.html.haml
  app/views/users/edit.html.haml
  spec/controllers/user/swaps_controller_spec.rb
Labels: CLA-signed

#949 app.json: make SERVER_HOST optional
  app.json
Labels: CLA-signed

#948 switch to Google TagManager
  .env.example
  app.json
  app/views/layouts/_google_analytics.html.haml
  app/views/layouts/_google_tag_manager_body.html.haml
  app/views/layouts/_google_tag_manager_head.html.haml
  app/views/layouts/application.html.haml
  spec/views/layouts/__snapshots__/application_by_election.snap
  spec/views/layouts/__snapshots__/application_general.snap
Labels: CLA-signed, analysis

#946 fix capitalisation of "Will vote"
  app/views/user/swaps/_swap_profile_inner.html.haml
Labels: CLA-signed

#954 Fix issue with missing emails
  app/controllers/user/constituencies_controller.rb
  app/controllers/user/swaps_controller.rb
  app/models/user.rb
  app/views/devise/passwords/new.html.erb
  app/views/mobile_phone/_form.html.haml
  app/views/mobile_phone/verify_token.html.haml
  app/views/users/edit.html.haml
  spec/controllers/user/swaps_controller_spec.rb
Labels: CLA-signed

#955 Prevent name from being an email
  app/models/user.rb
  spec/models/user_spec.rb
Labels: CLA-signed

#956 remove ActiveRecord#update_attributes which was removed in Rails 6.1
  app/controllers/mobile_phone_controller.rb
Labels: CLA-signed

#957 fix totally broken error handling on MessageBird verify_create failure
  app/controllers/mobile_phone_controller.rb
Labels: CLA-signed

#961 issue 951 willing party id nil
  app/controllers/mobile_phone_controller.rb
  app/views/users/review.haml
  spec/controllers/mobile_phone_controller_spec.rb
  spec/views/users/review.html.haml_spec.rb
Labels: frontend, CLA-signed, GE2024

#959 Ensure we have a mobile number before sending verification message
  app/controllers/mobile_phone_controller.rb
  spec/controllers/mobile_phone_controller_spec.rb
Labels: CLA-signed

#963 fix open-and-voting text
  app/views/home/_open_and_voting.html.haml
  spec/views/home/__snapshots__/_open_and_voting_by_election.snap
  spec/views/home/__snapshots__/_open_and_voting_general.snap
Labels: CLA-signed

#969 rake task to send email reminders to get swapping
  app/controllers/admin_controller.rb
  app/mailers/user_mailer.rb
  app/models/sent_email.rb
  app/models/user.rb
  app/views/home/_closed_wind_down.html.haml
  app/views/user_mailer/reminder_to_get_swapping.html.haml
  config/environments/development.rb
  lib/tasks/users.rake
  spec/models/user_spec.rb
  spec/views/home/__snapshots__/_closed_wind_down_by_election.snap
  spec/views/home/__snapshots__/_closed_wind_down_general.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election_open-and-voting.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election_open.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general_election_open-and-voting.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general_election_open.snap
  spec/views/user_mailer/reminder_to_get_swapping.html.haml_spec.rb
Labels: CLA-signed

#970 allow previewing email recipients
  app/models/user.rb
  lib/tasks/users.rake
  spec/models/user_spec.rb
Labels: CLA-signed

#973 fix utm params for reminder_to_get_swapping
  app/views/user_mailer/reminder_to_get_swapping.html.haml
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election_open-and-voting.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election_open.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general_election_open-and-voting.snap
  spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general_election_open.snap
Labels: CLA-signed

#965 user/edit: show errors if willing/preferred parties missing
  app/controllers/users_controller.rb
  spec/controllers/users_controller_spec.rb
Labels: CLA-signed

#974 Restore button for mobile verification
  app/controllers/users_controller.rb
  app/views/mobile_phone/_form.html.haml
Labels: CLA-signed

#978 Fix issue with willing/preferred party being lost on sign up
  app/views/home/_swap_form.html.haml
  spec/views/home/__snapshots__/_open_and_voting_by_election.snap
  spec/views/home/__snapshots__/_open_and_voting_general.snap
  spec/views/home/__snapshots__/_open_pre_elections_by_election.snap
  spec/views/home/__snapshots__/_open_pre_elections_general.snap
Labels: CLA-signed

#971 send reminders to review pending swaps
  app/controllers/admin_controller.rb
  app/mailers/user_mailer.rb
  app/models/sent_email.rb
  app/models/user.rb
  app/views/user_mailer/reminder_to_accept_swap.html.haml
  lib/tasks/users.rake
  spec/views/user_mailer/__snapshots__/reminder_to_accept_swap_by_election.snap
  spec/views/user_mailer/__snapshots__/reminder_to_accept_swap_general.snap
  spec/views/user_mailer/reminder_to_accept_swap.html.haml_spec.rb
Labels: CLA-signed
